# .air.toml

[build]
  cmd = "go build -o main ."
  bin = "main"
  full_bin = "./main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["vendor", "tmp", "node_modules"]
  exclude_file = []
  delay = 1000
  stop_on_error = true

[log]
  time = true

[color]
  main = "yellow"
