services:
  database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pg_db_data:/var/lib/postgresql/data
    networks:
      - fibernet

volumes:
  pg_db_data:
    driver: local

networks:
  fibernet:
    driver: bridge